version: "3.9"
services:
#*****************************************************************************
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgresql
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
