version: "3.9"
services:
#*****************************************************************************
  postgresql:
    restart: always
    #image: postgres:14.0
    image: harbor.kubeadm.ru/mirror.docker.hub/library/postgres:14.0
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=password123
    expose:
      - "5432"
    volumes:
      - "/media/data/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - gitlab
#*****************************************************************************
  redis:
    restart: always
    #image: redis:6.2.6
    image: harbor.kubeadm.ru/mirror.docker.hub/library/redis:6.2.6
    container_name: redis
    expose:
      - "6379"
    volumes:
      - "/media/data/redis/data:/data"
    networks:
      - gitlab
#*****************************************************************************
  gitlab_app:
    restart: always
    #image: 'gitlab/gitlab-ce:14.4.0-ce.0'
    image: 'harbor.kubeadm.ru/mirror.docker.hub/gitlab/gitlab-ce:14.4.0-ce.0'
    hostname: 'gitlab_app'
    container_name: gitlab_app
    expose:
      - "8081"
    volumes:
      - "/media/data/gitlab/config:/etc/gitlab"
      - "/media/data/gitlab/data:/var/opt/gitlab"
      - "/media/data/gitlab/logs:/var/log/gitlab"
    shm_size: '1024m'
    ports:
      - "8022:22"
    depends_on:
      - postgresql
      - redis
    links:
      - postgresql
      - redis
    networks:
      - gitlab
#*****************************************************************************
  nginx:
    restart: always
    #image: nginx:1.22
    image: harbor.kubeadm.ru/mirror.docker.hub/library/nginx:1.22
    container_name: nginx
    volumes:
      - "/media/data/nginx/conf/gitlab.crt:/etc/nginx/gitlab.crt:ro"
      - "/media/data/nginx/conf/gitlab.key:/etc/nginx/gitlab.key:ro"
      - "/media/data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/media/data/nginx/conf/gitlab-http.conf:/etc/nginx/conf.d/gitlab-http.conf:ro"
      - "/media/data/nginx/logs:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gitlab_app
    links:
      - gitlab_app
    networks:
      - gitlab
#*****************************************************************************  
networks:
  gitlab:
    driver: bridge
#*****************************************************************************
