version: '3'
services:
#***************************************************************
  prometheus:
    image: harbor.kubeadm.ru/mirror.docker.hub/prom/prometheus:latest
    volumes:
      - "prometheus-data:/etc/prometheus"
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - prometheus-net
#***************************************************************
  node-exporter:
    image: harbor.kubeadm.ru/mirror.docker.hub/prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - prometheus-net
#***************************************************************
  grafana:
    image: harbor.kubeadm.ru/mirror.docker.hub/grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - "grafana-data:/var/lib/grafana"
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - prometheus-net
#***************************************************************
volumes:
  prometheus-data:
  grafana-data:

networks:
  prometheus-net:
    driver: bridge
